INSERT INTO public.todo (id,text,completed,created_at) VALUES
(1, 'Acesto orum ad nullam de aris ut, efficiantur imad ab laetam si nobis exmultamen esse.', DEFAULT, DEFAULT),
(2, 'Potiorem homin contra concordant conquis.', DEFAULT, DEFAULT),
(3, 'Omi quid satiabilit quoddam venire appetenim a.', DEFAULT, DEFAULT),
(4, 'Potest praesid ex gendos ant, scientia solum epicet suo etiam qui dicta.', DEFAULT, DEFAULT),
(5, 'Et responender se e physicis nullo summum, ere quae et vero timumquam sent quibusu.', DEFAULT, DEFAULT),
(6, 'Ut video mihi maxime alest, unum habet aut minimpedien consequantur congressuscip.', DEFAULT, DEFAULT),
(7, 'Expeten domo tum parta inum saepe, dignitione de a liberos tum se homo qua.', DEFAULT, DEFAULT),
(8, 'Homere nobis ex voluptate mihi possit vero, inclusae a gymnasia as poteramic ut vita.', DEFAULT, DEFAULT),
(9, 'Homin delectatem et quam as desis.', DEFAULT, DEFAULT),
(10, 'Inum torem nec vire dubio mihi illum per.', DEFAULT, DEFAULT),
(11, 'Et rerum deorum dialectet orteat.', DEFAULT, DEFAULT),
(12, 'Delecce perangore multi et illud, publictorquat is magisse ipsas referin neque sive.', DEFAULT, DEFAULT),
(13, 'Siculassum eturus modum missimo iud quantum inis.', DEFAULT, DEFAULT),
(14, 'Nihillo cohaeres aperta probartemper sunt.', DEFAULT, DEFAULT),
(15, 'Quaedamicar recoristun neque a esse perspicuum.', DEFAULT, DEFAULT),
(16, 'Quam repugientiam neque es enim tamentur provinandum, nobisse hominesse sublatincur eosque et corpus consequi itur.', DEFAULT, DEFAULT),
(17, 'Sit totellatin bonae has et albucius diu efficerit, quidam gravisse si m nondum.', DEFAULT, DEFAULT),
(18, 'Posse si erunturben a quibus enda necesse tem, desid in nec undia satiabillus afferre.', DEFAULT, DEFAULT),
(19, 'Hac paulo a et est falsariam verbum sic, esse monstruosi idua aut debilitur non mediocritud haec.', DEFAULT, DEFAULT),
(20, 'Ident fruuntur noscertae et proptervalet neque es.', DEFAULT, DEFAULT);
