// eslint-disable-next-line @typescript-eslint/triple-slash-reference
/// <reference path=".snaplet/snaplet.d.ts" />
// This config was generated by Snaplet make sure to check it over before using it.
import { copycat, faker } from "@snaplet/copycat";
import { defineConfig } from "snaplet";
copycat.setHashKey("+6G/0WCWRdSsNesA");
export default defineConfig({
  generate: {
    async run(snaplet) {
      await snaplet.$pipe([
        snaplet.user((x) => x(5)),
        snaplet.todo((x) => x(100, () => ({
          vote: (x) => x(
            20, () => ({
              value: ({seed}) => copycat.oneOf(seed, ["UPVOTE" as const, "DOWNVOTE" as const])
            })
          )
        })),
        {autoConnect: true}
      )
    ]) 
    },
  },
});
